updewsprado/dewslandslide-htdocs

goldF/js/dewslandslide/dewschatterbox.js

Changes the title to Sitename or Recipient in the chatterbox

Changes the Title to Sitename / Recipient in Chatterbox

---

goldF/css/dewslandslide/dewschatterbox.css
goldF/js/dewslandslide/dewschatterbox.js

Added Css and JS for Create and Edit Contact feauture

Added Css and JS for Create and Edit Contact feauture

---

goldF/js/dewslandslide/dewschatterbox.js

Early warning information template.

Added EWI Feature

---

goldF/js/dewslandslide/dewschatterbox.js

Added scroll to view old messages feature

Added scroll to view old messages feature

---

goldF/js/dewslandslide/dewschatterbox.js

Reverts updewsprado/dewslandslide-htdocs#10

Revert "Added scroll to view old messages feature"

---

goldF/js/dewslandslide/dewschatterbox.js

// var tempConn = new WebSocket('ws://localhost:5050');

Scroll old messages feature

---

goldF/js/dewslandslide/dewschatterbox.js

BugFix: Ewi vanished after the latest release

BugFix: Ewi vanished after the latest release

---

goldF/css/dewslandslide/dewschatterbox.css
goldF/js/dewslandslide/dewschatterbox.js

Search message feature

---

goldF/css/dewslandslide/dewschatterbox.css
goldF/js/dewslandslide/dewschatterbox.js

Chatterbox: Flag Contacts for EWI Sending

Chatterbox: Flag Contacts for EWI Sending

---

goldF/js/dewslandslide/dewschatterbox.js

Added ewirecipient for the community_contacts array

---

goldF/css/dewslandslide/dewsresponsetracker.css
goldF/js/dewslandslide/dewsresponsetracker.js

Chatterbox response tracker

---

goldF/css/dewslandslide/dewschatterbox.css
goldF/js/dewslandslide/dewschatterbox.js

Chatterbox UI/UX Enhancement

---

goldF/css/dewslandslide/dewsresponsetracker.css
goldF/js/dewslandslide/dewsresponsetracker.js

Response tracker enhancement

---

goldF/js/dewslandslide/dewschatterbox.js

Improve ewi message composition

Improve ewi message composition

---

goldF/css/dewslandslide/dewschatterbox.css
goldF/js/dewslandslide/dewschatterbox.js

Group message for Dynaslope employee (FOR TESTING)

Employee group message for chatterbox

---

goldF/js/dewslandslide/dewschatterbox.js

Added scroll feature for Employee group message

---

goldF/css/dewslandslide/dewschatterbox.css
goldF/js/dewslandslide/dewschatterbox.js

Contact settings ui/ux enhancement

Contact settings ui/ux enhancement

---

goldF/css/dewslandslide/dewschatterbox.css
goldF/js/dewslandslide/dewschatterbox.js

Chatterbox timestamp sent/written enhancement

---

goldF/css/dewslandslide/dewschatterbox.css
goldF/js/dewslandslide/dewschatterbox.js

UI/UX polishing and BugFix

---

goldF/js/dewslandslide/dewschatterbox.js

Minor BugFix: Change input type number to text

Minor BugFix: Change input type number to text

---

goldF/js/dewslandslide/dewschatterbox.js

failed sending a message to multiple sites.

Mass message not working

---

css/dewslandslide/public_alert/monitoring_dashboard.css
js/dewslandslide/public_alert/alert_release_form.js
js/dewslandslide/public_alert/monitoring_dashboard.js
js/dewslandslide/reports/accomplishment_report.js
js/dewslandslide/reports/sitemaintenance_report.js

Commits and updates from m02 onwards...

Pull request on 2017-m03 branch

---

js/dewslandslide/communications/dewschatterbox.js

Reverts updewsprado/dewslandslide-htdocs#44

Revert "Fixed ws panel for testing"

---

js/dewslandslide/communications/dewschatterbox.js

Fixed merge issue

---

css/dewslandslide/public_alert/monitoring_events_individual.css
js/dewslandslide/public_alert/bulletin.js
js/dewslandslide/public_alert/monitoring_dashboard.js
js/dewslandslide/public_alert/monitoring_events_individual.js

- Inclusion of Gintags and automatic bulletin narrative entry for bulletin release
- Some design tweaks

Gintags on bulletin and automatic narrative on send

---

css/dewslandslide/dewschatterbox.css
css/dewslandslide/public_alert/monitoring_events_individual.css
js/dewslandslide/communications/dewschatterbox.js
js/dewslandslide/public_alert/bulletin.js
js/dewslandslide/public_alert/monitoring_dashboard.js
js/dewslandslide/public_alert/monitoring_events_individual.js

2017 m03 gintags feature

---

js/dewslandslide/communications/dewschatterbox.js

Fixed import issues

---

js/dewslandslide/communications/dewschatterbox.js

Modals not working properly

---

js/dewslandslide/communications/dewschatterbox.js

BugFix: Contact settings not working properly

BugFix: Contact settings not working properly

---

js/dewslandslide/communications/dewschatterbox.js

Added notification pop ups

---

js/dewslandslide/communications/dewschatterbox.js

BugFix: Missing function for unknown numbers quick inbox

BugFix: Missing function for unknown numbers quick inbox

---

js/dewslandslide/data_analysis/site_analysis.js

Staging Issues

---

js/dewslandslide/data_analysis/rainfall_scanner.js

-updated code rainfall_scanner.js

-updated code rainfall_scanner.js

---

js/dewslandslide/data_analysis/rainfall_scanner.js

2017 m03 ivy

---

js/dewslandslide/data_analysis/rainfall_scanner.js

-updated rainfall_scanner.php with default value

-updated rainfall_scanner.php with default value

---

js/dewslandslide/communications/dewschatterbox.js

Added REG8 as a default recipient

Added REG8 as a default recipient

---

js/dewslandslide/public_alert/bulletin.js

- Adding recipients of bulletin on narrative

- Bulletin sent indicator on button

---

js/dewslandslide/data_analysis/node_level.js
js/dewslandslide/data_analysis/surficial_level.js

- added gintags on surficial ground measurement

- added gintags on surficial ground measurement

---

js/dewslandslide/public_alert/alert_release_form.js
js/dewslandslide/public_alert/issues_and_reminders.js
js/dewslandslide/public_alert/monitoring_dashboard.js

- Some tweaks on bugs found on JS files

- Changes in issues and reminders module structure

---

js/dewslandslide/public_alert/alert_release_form.js
js/dewslandslide/public_alert/issues_and_reminders.js
js/dewslandslide/public_alert/monitoring_dashboard.js

M05 to M05 V2.

---

js/dewslandslide/data_analysis/rainfall_scanner.js
js/dewslandslide/data_analysis/site_analysis.js
js/dewslandslide/data_analysis/site_level.js
js/dewslandslide/public_alert/alert_release_form.js
js/dewslandslide/public_alert/bulletin.js
js/dewslandslide/public_alert/monitoring_dashboard.js
js/dewslandslide/reports/accomplishment_report.js

2017 m0708 john

---

js/dewslandslide/communications/dewschatterbox.js

Fix bug for Template creator A0 - Extended/Routine/Lowering

Fixed Template construction bug for A0 - Extended/Lowering/Routine

---

css/dewslandslide/dewsresponsetracker.css
js/dewslandslide/communications/dewsresponsetracker.js

merge m07 tasks.

---

css/dewslandslide/dewschatterbox_beta.css
js/dewslandslide/communications/dewschatterbox_beta.js
js/dewslandslide/reports/gintags_report.js

Enhance UI for Mobile devices

---

js/dewslandslide/communications/dewschatterbox_beta.js
js/dewslandslide/reports/gintags_report.js

2017 m09 john

---

js/dewslandslide/communications/dewschatterbox_beta.js

Added #GroundMeasReminder and #GroundMeasReminderAck

Added #GroundMeasReminder and #GroundMeasReminderAck to narratives

---

js/dewslandslide/communications/dewschatterbox_beta.js
js/dewslandslide/communications/dewsresponsetracker.js

Bug fixes and ui enhancement

---

css/dewslandslide/dewschatterbox_beta.css
js/dewslandslide/communications/dewsresponsive.js

Enhance UI chatterbox

---

js/dewslandslide/reports/gintags_report.js

Fixed date timepicker icons

---

js/dewslandslide/communications/dewsewi_template.js
js/dewslandslide/reports/gintags_report.js

Minor bug fixes

---

js/dewslandslide/communications/dewschatterbox.js
js/dewslandslide/communications/dewschatterbox_beta.js

Added New code for the old chatterbox

Added New code for the old chatterbox

---

js/dewslandslide/communications/dewschatterbox.js

Minor bugfix

---

js/dewslandslide/communications/dewschatterbox.js

Refactor No ACK Logic

---

js/dewslandslide/communications/dewschatterbox_beta.js

Change Ground Measurement narrative message

Change Ground Measurement narrative message

---

js/dewslandslide/communications/dewschatterbox_beta.js

Typo error

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fixed Loading modal for chatterbox new

Fixed Loading modal for chatterbox new

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fix Dashboard and chatterbox flagger

Fix Dashboard and chatterbox flagger

---

js/dewslandslide/communications/dewschatterbox_beta.js

QA Requests

---

js/dewslandslide/communications/dewschatterbox_beta.js

Ui request: Fix Narrative spacing

Ui request: Fix Narrative spacing

---

js/dewslandslide/reports/gintags_report.js

Fix gintags analytics anomalies

Fix gintags analytics anomalies

---

js/dewslandslide/public_alert/check_candidate_triggers.js

- Hotfix on alert generation on dashboard

---

js/dewslandslide/communications/dewschatterbox_beta.js

Hotfix: ND-Handling

---

js/dewslandslide/communications/dewschatterbox_beta.js

BugFix: Gintags narratives and Rx Issues

BugFix: Gintags narratives and Rx Issues

---

js/dewslandslide/communications/dewsewi_template.js

ewi template creator alert status fix

ewi template creator alert status fix

---

js/dewslandslide/communications/dewschatterbox_beta.js

added event/extended/routine indicator on quick site selection

added event/extended/routine indicator on quick site selection

---

css/dewslandslide/dewschatterbox_beta.css
js/dewslandslide/communications/dewschatterbox_beta.js

Initial commit for quick event inbox

Initial commit for quick event inbox

---

js/dewslandslide/communications/dewsresponsive.js

Fixed responsiveness

---

js/dewslandslide/communications/dewschatterbox_beta.js

Hot fix for no ack

---

js/dewslandslide/communications/dewschatterbox_beta.js

Hotfix for
- Narrative bug
- Investigation for lowering template

Hotfix for various bugs

---

js/dewslandslide/communications/dewschatterbox_beta.js

Template OCD issue FIx

---

js/dewslandslide/communications/dewschatterbox_beta.js

OCD issues

---

js/dewslandslide/communications/dewschatterbox_beta.js

BugFix for mesolong sites

---

js/dewslandslide/communications/dewschatterbox_beta.js

Bugs:
- No ack still appearing even if community acknowledged.
- PLGU included in extended monitoring
- Wrong trimming of numbers

Bug fix bug hunt 08222017

---

js/dewslandslide/communications/dewschatterbox_beta.js

Bugfix for Early warning info template

Minor bugfix for Early warning info template

---

js/dewslandslide/communications/dewschatterbox_beta.js

Hotfix for g0 s0 R0 statuses

---

js/dewslandslide/communications/dewschatterbox_beta.js

Enhance search filters

---

js/dewslandslide/public_alert/alert_release_form.js
js/dewslandslide/public_alert/check_candidate_triggers.js
js/dewslandslide/public_alert/monitoring_dashboard.js

- Recently lowered (A0) sites remain in latest table instead of extended if Day 0
- Extended release on dashboard

Bugfix branch

---

css/dewslandslide/dewschatterbox_beta.css
css/dewslandslide/gintags_manager.css
js/dewslandslide/communications/dewschatterbox_beta.js
js/dewslandslide/communications/gintags_manager.js

Gintags manager

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fix minor bugs

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fixed Minor UI Bugs

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fixed ewi dashboard issue regarding lowering and extended releases

Fixed ewi dashboard issue regarding lowering and extended releases

---

js/dewslandslide/communications/dewschatterbox_beta.js

Removed date for ewi scheduled the next day

Removed date for ewi scheduled the next day

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fixed routine section

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fixed minor UI bug for routine section

Fixed minor UI bug for routine section

---

js/dewslandslide/communications/dewschatterbox_beta.js

Multiple site per person tagging option

Polish feature

---

js/dewslandslide/communications/dewschatterbox_beta.js

BugFix: Chat bubble doesnt turn green

BugFix: Chat bubble doesnt turn green

---

js/dewslandslide/communications/dewschatterbox_beta.js

debug for GSM FAIL / SUCCESS testing

debug for GSM FAIL / SUCCESS testing

---

js/dewslandslide/communications/dewschatterbox_beta.js

finalize polishing of features

finalize polishing of features

---

js/dewslandslide/server_time.js

Added server time

---

js/dewslandslide/communications/dewschatterbox_beta.js

Debugger for fail / success gsm

Debugger for fail / success gsm

---

js/dewslandslide/communications/dewschatterbox_beta.js

Changed timestamp written / sent logic

Changed timestamp written / sent logic

---

css/dewslandslide/dewschatterbox_beta.css
js/dewslandslide/communications/dewschatterbox_beta.js

Finalize fail / success sms

---

js/dewslandslide/communications/dewschatterbox_beta.js

BugFix: sent indicator

---

js/dewslandslide/communications/dewschatterbox_beta.js

BugFix recent activities

---

js/dewslandslide/communications/dewschatterbox_beta.js

HotFix for A1-R internal alert for extended monitoring

HotFix for A1-R internal alert for extended monitoring

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fix red/blue for alerts quick group

Fix red/blue for alerts quick group

---

js/dewslandslide/data_analysis/manifestations.js
js/dewslandslide/data_analysis/manifestations_individual.js
js/dewslandslide/public_alert/alert_release_form.js
js/dewslandslide/public_alert/check_candidate_triggers.js
js/dewslandslide/public_alert/monitoring_dashboard.js

- Bug fixes on alert release form (m2)
- Manifestation API
- Bug fix on dashboard (ND as end-of-event release)

- Additional files for manifestation module

---

js/dewslandslide/communications/dewschatterbox_beta.js
js/dewslandslide/data_analysis/rainfall_scanner.js

Rainfall info template

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fixed LIP to LPA

---

js/dewslandslide/communications/dewschatterbox_beta.js

Remove province

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fixed Lowering default recipients

Fixed Lowering default recipients

---

js/dewslandslide/public_alert/bulletin.js
js/dewslandslide/public_alert/bulletin_maker.js

- fixed on edited bulletin behavior

- bulletin fix on validity if m0

---

js/dewslandslide/communications/dewschatterbox_beta.js

BugFix: School recipients unable to sent ewi

BugFix: School recipients unable to sent ewi

---

css/dewslandslide/dewschatterbox_beta.css
js/dewslandslide/communications/dewschatterbox_beta.js

Debug gsm / rpi sent / fail status

Debug gsm / rpi sent / fail status

---

js/dewslandslide/communications/dewschatterbox_beta.js

Fixed UI sms sent / failed

---

js/dewslandslide/communications/dewschatterbox_beta.js

removed debuggers and loggers

---

js/dewslandslide/communications/dewschatterbox_beta.js

Added vpn detection frontend

---

js/dewslandslide/communications/dewschatterbox_beta.js

Added vpn connection detector

---

js/dewslandslide/communications/dewschatterbox_beta.js

Testing vpn detection

---

js/dewslandslide/communications/dewschatterbox_beta.js

Finalize Front end for vpn detection

Finalize Front end for vpn detection

---

js/dewslandslide/communications/dewschatterbox_beta.js

Removed debugger and added cpu mem usage logger

Removed debugger and added cpu mem usage logger

---

js/dewslandslide/communications/dewschatterbox_beta.js

BugFix: llmc to lewc

---

js/dewslandslide/communications/dewschatterbox_wss.js

BugFix for chatterbox

---

js/dewslandslide/communications/dewschatterbox_initializer.js
js/dewslandslide/communications/dewschatterbox_wss.js

Added debug logs

---

js/dewslandslide/communications/dewschatterbox_wss.js

Added debuggers

---

js/dewslandslide/communications/dewschatterbox_wss.js

Added debbugers

---

js/dewslandslide/communications/dewschatterbox_wss.js

Removed debuggers

---

js/dewslandslide/communications/dewschatterbox_wss.js

Minor ui enhancement

---

js/dewslandslide/communications/dewschatterbox_wss.js

Finalize chatterbox sent status improvements

Finalize chatterbox sent status improvements

---

js/dewslandslide/communications/dewschatterbox_beta.js

BugFix for scroll up for old messages feature

BugFix for scroll up for old messages feature

---

css/dewslandslide/dewschatterbox_beta.css

Fixed contact suggestion alignment

---

js/dewslandslide/data_analysis/rainfall_plotter.js
js/dewslandslide/data_analysis/subsurface_column_plotter.js
js/dewslandslide/data_analysis/subsurface_node_plotter.js
js/dewslandslide/data_analysis/surficial_plotter.js

Fixed reset zoom position

---

js/dewslandslide/communications/dewschatterbox_wss.js

Moment format bugfix

---

js/dewslandslide/communications/dewschatterbox_wss.js

Changed subtract to diff in momentjs

Changed subtract to diff in momentjs
